### ISSUE TITLE
Support for itermcolors?

### ISSUE THREAD

**Issue by waivek** [xHN35RQ/apprentice-colorschemes#1]
Hello,

I am trying to get the apprentice color scheme for Windows `cmd.exe`.

I'm following the steps in this link - 

https://blogs.msdn.microsoft.com/commandline/2017/08/11/introducing-the-windows-console-colortool/

```
C:\Users\Toshiba PC\Desktop\vim\cmd_color>colortool.exe schemes\apprentice.itermcolors
Error loading ini file "./schemes\apprentice.itermcolors"
    for key "DARK_BLACK"
    the value "" is invalid
Could not find or load "schemes\apprentice.itermcolors"
```

**Comment by romainl** [comment]
> Could not find or load "schemes\apprentice.itermcolors"

Do you have that file in that directory? `>colortool apprentice` works fine, here:

<img width="100%" alt=">colortool apprentice" src="https://user-images.githubusercontent.com/344335/33232131-cd3ea088-d200-11e7-85f6-2bb60829fa1f.png">

**Comment by waivek** [comment]
That's so weird. It might be a noobish mistake on my part then. I think I'm doing everything right.

![capture](https://user-images.githubusercontent.com/5134623/33234500-c089223a-d24d-11e7-8802-68084ec37cb0.PNG)

**Comment by romainl** [comment]
You are supposed to put `apprentice.itermcolors` in the `schemes\` directory:

    C:\Users\Toshiba PC\Desktop\cmd_color\colortool
    C:\Users\Toshiba PC\Desktop\cmd_color\schemes\apprentice.itermcolors

From `>colortool` without argument:

    Usage:
        colortool.exe [options] <schemename>
    ColorTool is a utility for helping to set the color palette of the Windows Console.
    By default, applies the colors in the specified .itermcolors or .ini file to the current console window.
    This does NOT save the properties automatically. For that, you'll need to open the properties sheet and hit "Ok".
    Included should be a `schemes/` directory with a selection of schemes of both formats for examples.
    Feel free to add your own preferred scheme to that directory.
    Arguments:
        <schemename>: The name of a color scheme. ct will try to first load it as an .itermcolors color scheme.
                      If that fails, it will look for it as an .ini file color scheme.
    Options:
        -?, --help     : Display this help message
        -c, --current  : Print the color table for the currently applied scheme
        -q, --quiet    : Don't print the color table after applying
        -d, --defaults : Apply the scheme to only the defaults in the registry
        -b, --both     : Apply the scheme to both the current console and the defaults.
        -v, --version  : Display the version number

If none of that works I'm afraid I can't help you further.

**Comment by waivek** [comment]
Okay, I figured it out. Noobish mistake on my part. Closing the issue.

**Comment by siddudubey** [comment]
@waivek What was the mistake? It seems I'm also making the same noobish mistake :P
